apiVersion: v1
kind: Pod
metadata:
  name: result-app-pod
  labels:
    name: result-app-pod
    app: demo-voter-app
spec:
  containers:
    - name: result-app
      image: dockersamples/examplevotingapp_vote
      ports:
       - containerPort: 80